language: cpp

os:
  - osx
  - linux

compiler:
  - g++
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install qt5; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then echo y | sudo add-apt-repository ppa:beineri/opt-qt55; sudo apt-get update && sudo apt-get install -y qt55base; fi

before_script: cmake .

script:
  - make