language: cpp

os:
  - osx

compiler:
  - g++
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install cmake && brew install qt5; fi

before_script: cmake .

script:
  - make