language: cpp

os:
  - osx
  - linux

compiler:
  - g++
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install qt5; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y qtbase5-dev; fi

before_script: cmake .

script:
  - make